name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FAIL_LEVEL: WARNING
  ENV_TYPE: pipenv
  CHICAGO_INCIDENT_DATABASE_USER: test_user
  CHICAGO_INCIDENT_DATABASE_PASSWORD: 1234

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install pipenv
    - name: Run Tests
      run: |
        cd backend/
        pipenv install
        pipenv run ./manage.py test
