name: 311 Chicago Incidents CI

on: [push]

env:
  FAIL_LEVEL: WARNING
  ENV_TYPE: pipenv
  CHICAGO_INCIDENT_DATABASE_USER: test_user
  CHICAGO_INCIDENT_DATABASE_PASSWORD: password

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    
    services:
      postgres:
        image: postgres:12.4
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: chicago_incident_development_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Install Dependencies
      run: |
        pip install pipenv
        cd backend/
        pipenv install
    - name: Run migrations
      run: |
        cd backend/
        pipenv run ./manage.py migrate
    - name: Run Tests
      run: |
        cd backend/
        pipenv run ./manage.py test
