name: Vue.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: Build & Lint
      run: |
        cd frontend/
        yarn install
        yarn run build
        yarn run lint
